## Q1:
Write a function so that the columns of the output matrix are powers of the input
vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [11]:
import numpy as np

In [32]:
def atv_matrix(arr, N=None, increasing=False):
    if N==None:
        N = len(arr)
    mat = np.zeros((len(arr), N), dtype=int)
    for i in range(N):
        for j in range(len(arr)):
            mat[j][i] = arr[j]**i 
    if increasing == True:
        return mat
    else:
        for i in range(N//2):
            for j in range(len(arr)):
                mat[j][i], mat[j][N-i-1] = mat[j][N-i-1], mat[j][i]
        return mat

In [36]:
atv_matrix([1,2,3,4], 5, increasing=True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256]])

In [37]:
atv_matrix([1,2,3,4], 5)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1]])

## Q2:
Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [2]:
def moving_avg(arr, k):
    l = []
    for i in range(len(arr)-k+1):
        l.append(arr[i:i+k].mean())
    return l

In [3]:
arr = np.array( [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
arr

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [4]:
print(moving_avg(arr, 3))

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
